export enum CONTACT_TAG_ENUM {
  FAVOURITE = "FAVOURITE",
  NEW = "NEW",
  FAMILY = "FAMILY",
  FRIEND = "FRIEND",
  COLLEAGUE = "COLLEAGUE",
  CLIENT = "CLIENT",
  SUPPLIER = "SUPPLIER",
  EMPLOYEE = "EMPLOYEE",
  INVESTOR = "INVESTOR",
  VENDOR = "VENDOR",
  OTHER = "OTHER",
}
