export enum PROFILE_COMPONENT_TYPE {
    PHONE = "phone",
    EMAIL = "email",
    IMAGE = "img",
    TEXT = "text",
    HEADING = "heading",
    PARAGRAPH = "paragraph",
    LINK = "link",
    VIDEO = "video",
    MAP = "map",
    MICROSOFT_WORD = "microsoft_word",
    PDF = "pdf",
    FACEBOOK = "facebook",
    TWITTER = "twitter",
    INSTAGRAM = "instagram",
    LINKEDIN = "linkedin",
    TIKTOK = "tiktok",
    FACEBOOK_POST = "facebook_post",
    TWITTER_POST = "twitter_post",
    INSTAGRAM_POST = "instagram_post",
    LINKEDIN_POST = "linkedin_post",
    TIKTOK_POST = "tiktok_post",
    YOUTUBE_POST = "youtube_post",
    SNAPCHAT = "snapchat",
    PINTEREST = "pinterest",
    DISCORD = "discord",
    SLACK = "slack",
    YOUTUBE = "youtube",
    TWITCH = "twitch",
    GITHUB = "github",
    TELEGRAM = "telegram",
    WHATSAPP = "whatsapp",
    SPOTIFY = "spotify",
    APPLE_MUSIC = "apple_music",
    AMAZON_MUSIC = "amazon_music",
    DRIBBBLE = "dribbble",
    BEHANCE = "behance",
    PAYPAL = "paypal",
    STRIPE = "stripe",
    AMAZON_PAY = "amazon_pay",
    APPLE_PAY = "apple_pay",
    GOOGLE_MEET = "google_meet",
    MICROSOFT_TEAMS = "microsoft_teams",
    INFO = "info",
    ZOOM = "zoom",
  };
  
  export enum PROFILE_COMPONENT_CATEGORY {
    MAIL = "mail",
    LINK = "link",
    VIDEO = "video",
    MAP = "map",
    FILE = "file",
    PHONE = "phone",
    PAYMENT = "payment",
    MUSIC = "music",
    IMAGE = "img",
    TEXT = "text",
    SOCIAL_EMBED = "social_embed",
  };

  export enum CONNECTION_REQUEST_STATUS {
    PENDING = "pending",
    ACCEPTED = "accepted",
    REJECTED = "rejected",
  };
  
  export enum CONTACT_TAG_TYPE {
    FAMILY = "family",
    FRIEND = "friend",
    COLLEAGUE = "colleague",
    CLIENT = "client",
    SUPPLIER = "supplier",
    EMPLOYEE = "empolyee",
    INVESTOR = "investor",
    VENDOR = "vendor",
    OTHER = "Other",
  };
  