import { Contact, CONTACT_TAG_TYPE } from "@/lib/type";

export async function fetchContactData(): Promise<Contact[]> {
  return data;
}

const data: Contact[] = [
  {
    UserCardID: 1,
    connectionID: 1,
    connectedUserCardID: 1,
    connectedUserID: 1,
    connectedUsername: "Mario",
    connectedUserOccupation: "Software Engineer",
    connectedUserCompany: "Apple Inc.",
    connectedUserImage: "",
    connectedDate: new Date("2023-01-15T10:30:00"),
    tag: CONTACT_TAG_TYPE.FAMILY,
  },
  {
    UserCardID: 2,
    connectionID: 3,
    connectedUserCardID: 1,
    connectedUserID: 1,
    connectedUsername: "Mario AppleBanana Lwin Aung Kyaw Za Ko Ko",
    connectedUserOccupation: "Software Engineer",
    connectedUserCompany: "Apple Inc.",
    connectedUserImage:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSL0eH9M7zlW3oznwVU_iFfBBm9NvGK699uWfVawLlQ_zkifc__LtOS7cM6t89WCTYEYGteM__Izy8uSLt2yA3h9mHXIWClQyqwVhRsFPsHua1Awbtn-KwmvKv5TqPKU9qTA7tvFms&usqp=CAc",
    connectedDate: new Date("2023-01-15T10:30:00"),
    tag: CONTACT_TAG_TYPE.FRIEND,
  },
  {
    UserCardID: 1,
    connectionID: 1,
    connectedUserCardID: 1,
    connectedUserID: 1,
    connectedUsername: "Mario",
    connectedUserOccupation: "Software Engineer",
    connectedUserCompany: "Apple Inc.",
    connectedUserImage: "",
    connectedDate: new Date("2023-01-15T10:30:00"),
    tag: CONTACT_TAG_TYPE.FAMILY,
  },
  {
    UserCardID: 2,
    connectionID: 3,
    connectedUserCardID: 1,
    connectedUserID: 1,
    connectedUsername: "Mario AppleBanana Lwin Aung Kyaw Za Ko Ko",
    connectedUserOccupation: "Software Engineer",
    connectedUserCompany: "Apple Inc.",
    connectedUserImage:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSL0eH9M7zlW3oznwVU_iFfBBm9NvGK699uWfVawLlQ_zkifc__LtOS7cM6t89WCTYEYGteM__Izy8uSLt2yA3h9mHXIWClQyqwVhRsFPsHua1Awbtn-KwmvKv5TqPKU9qTA7tvFms&usqp=CAc",
    connectedDate: new Date("2023-01-15T10:30:00"),
    tag: CONTACT_TAG_TYPE.FRIEND,
  },
  {
    UserCardID: 1,
    connectionID: 1,
    connectedUserCardID: 1,
    connectedUserID: 1,
    connectedUsername: "Mario",
    connectedUserOccupation: "Software Engineer",
    connectedUserCompany: "Apple Inc.",
    connectedUserImage: "",
    connectedDate: new Date("2023-01-15T10:30:00"),
    tag: CONTACT_TAG_TYPE.FAMILY,
  },
  {
    UserCardID: 2,
    connectionID: 3,
    connectedUserCardID: 1,
    connectedUserID: 1,
    connectedUsername: "Mario AppleBanana Lwin Aung Kyaw Za Ko Ko",
    connectedUserOccupation: "Software Engineer",
    connectedUserCompany: "Apple Inc.",
    connectedUserImage:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSL0eH9M7zlW3oznwVU_iFfBBm9NvGK699uWfVawLlQ_zkifc__LtOS7cM6t89WCTYEYGteM__Izy8uSLt2yA3h9mHXIWClQyqwVhRsFPsHua1Awbtn-KwmvKv5TqPKU9qTA7tvFms&usqp=CAc",
    connectedDate: new Date("2023-01-15T10:30:00"),
    tag: CONTACT_TAG_TYPE.FRIEND,
  },
  {
    UserCardID: 1,
    connectionID: 1,
    connectedUserCardID: 1,
    connectedUserID: 1,
    connectedUsername: "Mario",
    connectedUserOccupation: "Software Engineer",
    connectedUserCompany: "Apple Inc.",
    connectedUserImage: "",
    connectedDate: new Date("2023-01-15T10:30:00"),
    tag: CONTACT_TAG_TYPE.FAMILY,
  },
  {
    UserCardID: 2,
    connectionID: 3,
    connectedUserCardID: 1,
    connectedUserID: 1,
    connectedUsername: "Mario AppleBanana Lwin Aung Kyaw Za Ko Ko",
    connectedUserOccupation: "Software Engineer",
    connectedUserCompany: "Apple Inc.",
    connectedUserImage:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSL0eH9M7zlW3oznwVU_iFfBBm9NvGK699uWfVawLlQ_zkifc__LtOS7cM6t89WCTYEYGteM__Izy8uSLt2yA3h9mHXIWClQyqwVhRsFPsHua1Awbtn-KwmvKv5TqPKU9qTA7tvFms&usqp=CAc",
    connectedDate: new Date("2023-01-15T10:30:00"),
    tag: CONTACT_TAG_TYPE.FRIEND,
  },
  {
    UserCardID: 1,
    connectionID: 1,
    connectedUserCardID: 1,
    connectedUserID: 1,
    connectedUsername: "Mario",
    connectedUserOccupation: "Software Engineer",
    connectedUserCompany: "Apple Inc.",
    connectedUserImage: "",
    connectedDate: new Date("2023-01-15T10:30:00"),
    tag: CONTACT_TAG_TYPE.FAMILY,
  },
  {
    UserCardID: 2,
    connectionID: 3,
    connectedUserCardID: 1,
    connectedUserID: 1,
    connectedUsername: "Mario AppleBanana Lwin Aung Kyaw Za Ko Ko",
    connectedUserOccupation: "Software Engineer",
    connectedUserCompany: "Apple Inc.",
    connectedUserImage:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSL0eH9M7zlW3oznwVU_iFfBBm9NvGK699uWfVawLlQ_zkifc__LtOS7cM6t89WCTYEYGteM__Izy8uSLt2yA3h9mHXIWClQyqwVhRsFPsHua1Awbtn-KwmvKv5TqPKU9qTA7tvFms&usqp=CAc",
    connectedDate: new Date("2023-01-15T10:30:00"),
    tag: CONTACT_TAG_TYPE.FRIEND,
  },
  {
    UserCardID: 1,
    connectionID: 1,
    connectedUserCardID: 1,
    connectedUserID: 1,
    connectedUsername: "Mario",
    connectedUserOccupation: "Software Engineer",
    connectedUserCompany: "Apple Inc.",
    connectedUserImage: "",
    connectedDate: new Date("2023-01-15T10:30:00"),
    tag: CONTACT_TAG_TYPE.FAMILY,
  },
  {
    UserCardID: 2,
    connectionID: 3,
    connectedUserCardID: 1,
    connectedUserID: 1,
    connectedUsername: "Mario AppleBanana Lwin Aung Kyaw Za Ko Ko",
    connectedUserOccupation: "Software Engineer",
    connectedUserCompany: "Apple Inc.",
    connectedUserImage:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSL0eH9M7zlW3oznwVU_iFfBBm9NvGK699uWfVawLlQ_zkifc__LtOS7cM6t89WCTYEYGteM__Izy8uSLt2yA3h9mHXIWClQyqwVhRsFPsHua1Awbtn-KwmvKv5TqPKU9qTA7tvFms&usqp=CAc",
    connectedDate: new Date("2023-01-15T10:30:00"),
    tag: CONTACT_TAG_TYPE.FRIEND,
  },
];
