import {
  FaEnvelope,
  FaLink,
  FaGithub,
  FaLinkedin,
  FaFacebook,
  FaInstagram,
  FaTwitter,
  FaTiktok,
  FaSnapchat,
  FaPinterest,
  FaPhone,
  FaWhatsapp,
  FaTelegram,
  FaVideo,
  FaMusic,
  FaPaypal,
  FaGoogle,
  FaAmazon,
  FaSpotify,
  FaYoutube,
  FaApple,
  FaDiscord,
  FaSlack,
  FaTwitch,
  FaDribbble,
  FaBehance,
  FaMapMarkerAlt,
} from "react-icons/fa";
import { PROFILE_COMPONENT_TYPE } from "./type";
import { PiTextAaLight } from "react-icons/pi";
import { TbInfoSquareRoundedFilled } from "react-icons/tb";
import { LuImagePlus } from "react-icons/lu";

export const typeIconMap = {
  [PROFILE_COMPONENT_TYPE.EMAIL]: <FaEnvelope />,
  [PROFILE_COMPONENT_TYPE.LINK]: <FaLink />,
  [PROFILE_COMPONENT_TYPE.GITHUB]: <FaGithub />,
  [PROFILE_COMPONENT_TYPE.LINKEDIN]: <FaLinkedin />,
  [PROFILE_COMPONENT_TYPE.FACEBOOK]: <FaFacebook />,
  [PROFILE_COMPONENT_TYPE.INSTAGRAM]: <FaInstagram />,
  [PROFILE_COMPONENT_TYPE.MAP]: <FaMapMarkerAlt />,
  [PROFILE_COMPONENT_TYPE.TWITTER]: <FaTwitter />,
  [PROFILE_COMPONENT_TYPE.TIKTOK]: <FaTiktok />,
  [PROFILE_COMPONENT_TYPE.SNAPCHAT]: <FaSnapchat />,
  [PROFILE_COMPONENT_TYPE.PINTEREST]: <FaPinterest />,
  [PROFILE_COMPONENT_TYPE.DISCORD]: <FaDiscord />,
  [PROFILE_COMPONENT_TYPE.SLACK]: <FaSlack />,
  [PROFILE_COMPONENT_TYPE.PHONE]: <FaPhone />,
  [PROFILE_COMPONENT_TYPE.WHATSAPP]: <FaWhatsapp />,
  [PROFILE_COMPONENT_TYPE.TELEGRAM]: <FaTelegram />,
  [PROFILE_COMPONENT_TYPE.VIDEO]: <FaVideo />,
  [PROFILE_COMPONENT_TYPE.GOOGLE_MEET]: <FaGoogle />,
  [PROFILE_COMPONENT_TYPE.MICROSOFT_TEAMS]: <FaVideo />,
  [PROFILE_COMPONENT_TYPE.PAYPAL]: <FaPaypal />,
  [PROFILE_COMPONENT_TYPE.STRIPE]: <FaLink />,
  [PROFILE_COMPONENT_TYPE.AMAZON_PAY]: <FaAmazon />,
  [PROFILE_COMPONENT_TYPE.APPLE_PAY]: <FaApple />,
  [PROFILE_COMPONENT_TYPE.YOUTUBE]: <FaYoutube />,
  [PROFILE_COMPONENT_TYPE.TWITCH]: <FaTwitch />,
  [PROFILE_COMPONENT_TYPE.SPOTIFY]: <FaSpotify />,
  [PROFILE_COMPONENT_TYPE.APPLE_MUSIC]: <FaMusic />,
  [PROFILE_COMPONENT_TYPE.AMAZON_MUSIC]: <FaAmazon />,
  [PROFILE_COMPONENT_TYPE.DRIBBBLE]: <FaDribbble />,
  [PROFILE_COMPONENT_TYPE.BEHANCE]: <FaBehance />,
  [PROFILE_COMPONENT_TYPE.TEXT]: <PiTextAaLight />,
  [PROFILE_COMPONENT_TYPE.FILE]: <FaLink />,
  [PROFILE_COMPONENT_TYPE.IMAGE]: <LuImagePlus />,
  [PROFILE_COMPONENT_TYPE.INFO]: <TbInfoSquareRoundedFilled />,
};
