import { DesignModel } from "@/core/_domain/models/design.model";
import { InformationModel } from "@/core/_domain/models/information.model";
import {
  PROFILE_COMPONENT_CATEGORY,
  PROFILE_COMPONENT_TYPE,
} from "@/lib/types/enums";
import { ProfileCard, ProfileDndComponent } from "@/lib/types/types";

//...................PROFILE DATA............................
// export const profileDndComponents: ProfileDndComponent[] = [
//   {
//     id: "103",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.EMAIL,
//     category: PROFILE_COMPONENT_CATEGORY.MAIL,
//     display_text: "Work Email",
//     value: "john.doe@example.com",
//     position: 0,
//   },
//   {
//     id: "104",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.LINK,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "Personal Website",
//     value: "https://johndoe.com",
//     position: 1,
//   },
//   {
//     id: "106",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.PHONE,
//     category: PROFILE_COMPONENT_CATEGORY.PHONE,
//     display_text: "Mobile",
//     value: "6594832945",
//     position: 2,
//   },
//   {
//     id: "107",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.WHATSAPP,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "WhatsApp Number",
//     value: "https://wa.me/6594832945",
//     position: 3,
//   },
//   {
//     id: "108",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.TELEGRAM,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "My Telegram",
//     value: "https://t.me/Kyaw_Za_Yan_Naing",
//     position: 4,
//   },
//   {
//     id: "102",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.HEADING,
//     category: PROFILE_COMPONENT_CATEGORY.TEXT,
//     display_text: "Name",
//     value: "My Best Image!",
//     position: 5,
//   },
//   {
//     id: "101",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.IMAGE,
//     category: PROFILE_COMPONENT_CATEGORY.IMAGE,
//     display_text: "",
//     value: "https://uz4l01v58c.ufs.sh/f/vgsYHuXFuRcjfOy3AK6SI2G6hNXCYW8TlxQ50wbMou7pare3",
//     position: 6,
//   },
//   {
//     id: "200",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.HEADING,
//     category: PROFILE_COMPONENT_CATEGORY.TEXT,
//     display_text: "Name",
//     value: "My Address",
//     position: 7,
//   },
//   {
//     id: "109",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.YOUTUBE,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "My Youtube Channel",
//     value: "https://www.youtube.com/channel/UCBo1hnzxV9rz3WVsv__Rn1g",
//     position: 8,
//   },
//   {
//     id: "201",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.HEADING,
//     category: PROFILE_COMPONENT_CATEGORY.TEXT,
//     display_text: "Name",
//     value: "My Social Media Links",
//     position: 9,
//   },
//   {
//     id: "110",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.DISCORD,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "Discord Account",
//     value: "dice#3040",
//     position: 10,
//   },
//   {
//     id: "111",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.GITHUB,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "GitHub Profile",
//     value: "https://github.com/johndoe",
//     position: 11,
//   },
//   {
//     id: "112",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.LINKEDIN,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "LinkedIn Profile",
//     value: "https://www.linkedin.com/in/johndoe",
//     position: 12,
//   },
//   {
//     id: "113",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.FACEBOOK,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "Facebook Page",
//     value: "https://www.facebook.com/johndoe",
//     position: 13,
//   },
//   {
//     id: "114",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.INSTAGRAM,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "Instagram Profile",
//     value: "https://www.instagram.com/johndoe",
//     position: 14,
//   },
//   {
//     id: "115",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.TWITTER,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "Twitter Profile",
//     value: "https://twitter.com/johndoe",
//     position: 15,
//   },
//   {
//     id: "116",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.TIKTOK,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "TikTok Profile",
//     value: "https://www.tiktok.com/@johndoe",
//     position: 16,
//   },
//   {
//     id: "117",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.PINTEREST,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "Pinterest Board",
//     value: "https://www.pinterest.com/johndoe/myboard",
//     position: 17,
//   },
//   {
//     id: "119",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.PAYPAL,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "PayPal Link",
//     value: "https://www.paypal.com/paypalme/johndoe",
//     position: 18,
//   },
//   {
//     id: "120",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.ZOOM,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "Zoom Meeting",
//     value: "https://zoom.us/j/1234567890",
//     position: 19,
//   },
//   {
//     id: "121",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.GOOGLE_MEET,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "Google Meet",
//     value: "https://meet.google.com/abc-defg-hij",
//     position: 20,
//   },
//   {
//     id: "122",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.MICROSOFT_TEAMS,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "Microsoft Teams Meeting",
//     value: "https://teams.microsoft.com/l/meetup-join/abc123",
//     position: 21,
//   },
//   {
//     id: "123",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.DRIBBBLE,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "Dribbble Profile",
//     value: "https://dribbble.com/johndoe",
//     position: 22,
//   },
//   {
//     id: "124",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.BEHANCE,
//     category: PROFILE_COMPONENT_CATEGORY.LINK,
//     display_text: "Behance Portfolio",
//     value: "https://www.behance.net/johndoe",
//     position: 23,
//   },
//   {
//     id: "125",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.LINKEDIN_POST,
//     category: PROFILE_COMPONENT_CATEGORY.SOCIAL_EMBED,
//     display_text: "LinkedIn Post",
//     value: "https://www.linkedin.com/embed/feed/update/urn:li:share:7329037915160834049?compact=1",
//     position: 24,
//   },
//   {
//     id: "126",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.TWITTER_POST,
//     category: PROFILE_COMPONENT_CATEGORY.SOCIAL_EMBED,
//     display_text: "Twitter Tweet",
//     value: "https://twitter.com/AppleSupport/status/1873769925375860807",
//     position: 25,
//   },
//   {
//     id: "127",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.INSTAGRAM_POST,
//     category: PROFILE_COMPONENT_CATEGORY.SOCIAL_EMBED,
//     display_text: "Instagram Post",
//     value: "https://www.instagram.com/p/DEOoN1KunCl/?utm_source=ig_web_copy_link",
//     position: 26,
//   },
//   {
//     id: "128",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.YOUTUBE_POST,
//     category: PROFILE_COMPONENT_CATEGORY.SOCIAL_EMBED,
//     display_text: "YouTube Video",
//     value: "https://www.youtube.com/watch?v=ekr2nIex040",
//     position: 27,
//   },
//   {
//     id: "129",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.FACEBOOK_POST,
//     category: PROFILE_COMPONENT_CATEGORY.SOCIAL_EMBED,
//     display_text: "Facebook Post",
//     value: "https://www.facebook.com/Genshinimpact/posts/pfbid02sCNWWoC7aGpE53Wp2Ja1TSLCQwopxyACnMfiiqLxL3ypbqvU8tCXy1cDJoYFrXqCl/",
//     position: 28,
//   },
//   {
//     id: "130",
//     card_id: "1",
//     type: PROFILE_COMPONENT_TYPE.TIKTOK_POST,
//     category: PROFILE_COMPONENT_CATEGORY.SOCIAL_EMBED,
//     display_text: "TikTok Post",
//     value: "https://www.tiktok.com/@wasted.a1/video/7253096002691894530?is_from_webapp=1&sender_device=pc&web_id=7454463793868195344",
//     position: 29,
//   },
// ];

// export const profileCard: ProfileCard[] = [
//   {
//     card_id: "1",
//     user_id: "1",
//     foreground_color: "#E6E6FA",
//     background_color: "#050505",
//     wave_color: "#FF6347",
//     layout: "classic",
//     wave_type: "wave_one",
//     image: "/image/profile.jpg",
//     logo_icon: "/image/profile.jpg",
//     prefix: "Mr.",
//     first_name: "John",
//     middle_name: "Arthur",
//     last_name: "Doe",
//     suffix: "Jr.",
//     quote: "Time and Tide wait for no man.",
//     preferred_name: "John Doe",
//     pronouns: "he/him",
//     title: "Dr.",
//     occupation: "Web Developer",
//     company: "Google",
//     message: "Hello world!",
//   },
//   {
//     card_id: "2",
//     user_id: "1",
//     foreground_color: "#050505",
//     background_color: "#ffffff",
//     wave_color: "#050505",
//     layout: "modern",
//     wave_type: "wave_two",
//     image: "/image/profile2.jpg",
//     logo_icon: "/image/logo2.jpg",
//     prefix: "Ms.",
//     first_name: "Jane",
//     middle_name: "Elizabeth",
//     last_name: "Smith",
//     suffix: "",
//     quote: "Dream big, work hard.",
//     preferred_name: "Jane Smith",
//     pronouns: "she/her",
//     title: "Ms.",
//     occupation: "Graphic Designer",
//     company: "Adobe",
//     message: "Let's create amazing designs!",
//   },
//   {
//     card_id: "3",
//     user_id: "1",
//     foreground_color: "#050505",
//     background_color: "#ffffff",
//     wave_color: "#050505",
//     layout: "layout_three",
//     wave_type: "wave_three",
//     image: "/image/profile3.jpg",
//     logo_icon: "/image/logo3.jpg",
//     prefix: "",
//     first_name: "Alex",
//     middle_name: "",
//     last_name: "Johnson",
//     suffix: "",
//     quote: "Innovation is key.",
//     preferred_name: "Alex Johnson",
//     pronouns: "they/them",
//     title: "Engineer",
//     occupation: "Software Engineer",
//     company: "Tesla",
//     message: "Driving the future of tech!",
//   },

//   //INITIAL DATA
//   {
//     card_id: "4",
//     user_id: "4",
//     foreground_color: "#E6E6FA",
//     background_color: "#050505",
//     wave_color: "#050505",
//     layout: "classic",
//     wave_type: "wave_one",
//     image: "",
//     logo_icon: "",
//     prefix: "",
//     first_name: "",
//     middle_name: "",
//     last_name: "",
//     suffix: "",
//     quote: "",
//     preferred_name: "",
//     pronouns: "",
//     title: "",
//     occupation: "",
//     company: "",
//     message: "",
//   },
// ];

// export const design: DesignModel[] = [
//   {
//     id: 1,
//     cardId: "1",
//     foregroundColor: "#E6E6FA",
//     backgroundColor: "#050505",
//     backgroundImage: "/image/profile.jpg",
//     profileImage: "/image/profile.jpg",
//     layout: "classic"
//   },
//   {
//     id: 2,
//     cardId: "2",
//     foregroundColor: "#050505",
//     backgroundColor: "#ffffff",
//     backgroundImage: "/image/profile2.jpg",
//     profileImage: "/image/logo2.jpg",
//     layout: "modern"
//   },
//   {
//     id: 3,
//     cardId: "3",
//     foregroundColor: "#050505",
//     backgroundColor: "#ffffff",
//     backgroundImage: "/image/profile3.jpg",
//     profileImage: "/image/logo3.jpg",
//     layout: "layout_three"
//   },
//   {
//     id: 4,
//     cardId: "4",
//     foregroundColor: "#E6E6FA",
//     backgroundColor: "#050505",
//     backgroundImage: null,
//     profileImage: null,
//     layout: "classic"
//   }
// ];

// export const information: InformationModel[] = [
//   {
//     id: 1,
//     cardId: "1",
//     title: "Dr.",
//     fullName: "John Arthur Doe",
//     occupation: "Web Developer",
//     company: "Google",
//     message: "Hello world!",
//     quote: "Time and Tide wait for no man.",
//     prefix: "Mr.",
//     suffix: "Jr.",
//     preferredName: "John Doe",
//     pronouns: "he/him"
//   },
//   {
//     id: 2,
//     cardId: "2",
//     title: "Ms.",
//     fullName: "Jane Elizabeth Smith",
//     occupation: "Graphic Designer",
//     company: "Adobe",
//     message: "Let's create amazing designs!",
//     quote: "Dream big, work hard.",
//     prefix: "Ms.",
//     suffix: null,
//     preferredName: "Jane Smith",
//     pronouns: "she/her"
//   },
//   {
//     id: 3,
//     cardId: "3",
//     title: "Engineer",
//     fullName: "Alex Johnson",
//     occupation: "Software Engineer",
//     company: "Tesla",
//     message: "Driving the future of tech!",
//     quote: "Innovation is key.",
//     prefix: null,
//     suffix: null,
//     preferredName: "Alex Johnson",
//     pronouns: "they/them"
//   },
//   {
//     id: 4,
//     cardId: "4",
//     title: null,
//     fullName: "",
//     occupation: null,
//     company: null,
//     message: null,
//     quote: null,
//     prefix: null,
//     suffix: null,
//     preferredName: null,
//     pronouns: null
//   }
// ];

//.............................................................

// .................Create dummy contact data for the connection requests with sender details..........
// export const detailsContact: ConnectionRequestWithDetails[] = [
//   {
//     requestID: "1",
//     senderCardID: "1",
//     recieverCardID: "202",
//     status: CONNECTION_REQUEST_STATUS.PENDING,
//     created_at: new Date("2024-11-01T08:00:00Z"),
//     updated_at: new Date("2024-11-01T08:00:00Z"),
//     senderFullname: "John",
//     senderOccupation: "Software Engineer",
//     senderCompany: "Tech Corp",
//     senderImage: "",
//   },
//   {
//     requestID: "2",
//     senderCardID: "2",
//     recieverCardID: "203",
//     status: CONNECTION_REQUEST_STATUS.ACCEPTED,
//     created_at: new Date("2024-11-02T09:30:00Z"),
//     updated_at: new Date("2024-11-02T09:35:00Z"),
//     senderFullname: "Jane",
//     senderOccupation: "Product Manager",
//     senderCompany: "Innovate Inc.",
//     senderImage: "",
//   },
//   {
//     requestID: "3",
//     senderCardID: "3",
//     recieverCardID: "204",
//     status: CONNECTION_REQUEST_STATUS.REJECTED,
//     created_at: new Date("2024-11-03T10:00:00Z"),
//     updated_at: new Date("2024-11-03T10:05:00Z"),
//     senderFullname: "Michael",
//     senderOccupation: "Data Scientist",
//     senderCompany: "DataLab",
//     senderImage: "",
//   },
//   {
//     requestID: "4",
//     senderCardID: "104",
//     recieverCardID: "205",
//     status: CONNECTION_REQUEST_STATUS.PENDING,
//     created_at: new Date("2024-11-04T11:00:00Z"),
//     updated_at: new Date("2024-11-04T11:05:00Z"),
//     senderFullname: "Alice",
//     senderOccupation: "Marketing Lead",
//     senderCompany: "BrandCo",
//     senderImage: "",
//   },
//   {
//     requestID: "5",
//     senderCardID: "105",
//     recieverCardID: "206",
//     status: CONNECTION_REQUEST_STATUS.ACCEPTED,
//     created_at: new Date("2024-11-05T12:30:00Z"),
//     updated_at: new Date("2024-11-05T12:35:00Z"),
//     senderFullname: "Robert",
//     senderOccupation: "UX Designer",
//     senderCompany: "Designify",
//     senderImage: "",
//   },
// ];

// export const detailsContactData: ContactWithDetails[] = [
//   {
//     contactID: "1",
//     userCardID: "1",
//     contactPersonCardID: "1",
//     contactPersonID: "1",
//     contactPersonFullname: "John",
//     contactPersonOccupation: "Software Engineer",
//     contactPersonCompany: "Tech Innovators Ltd.",
//     contactPersonImage: "",
//     created_at: new Date("2023-01-15T10:30:00"),
//     updated_at: new Date("2023-01-15T10:30:00"),
//     tag: CONTACT_TAG_TYPE.FAMILY,
//     note: "SIM student",
//   },
//   {
//     contactID: "3",
//     userCardID: "1",
//     contactPersonCardID: "1",
//     contactPersonID: "1",
//     contactPersonFullname: "Alice",
//     contactPersonOccupation: "Marketing Manager",
//     contactPersonCompany: "Creative Solutions",
//     contactPersonImage: "",
//     created_at: new Date("2023-01-16T14:00:00"),
//     updated_at: new Date("2023-01-16T14:00:00"),
//     tag: CONTACT_TAG_TYPE.FRIEND,
//   },
//   {
//     contactID: "2",
//     userCardID: "1",
//     contactPersonCardID: "2",
//     contactPersonID: "2",
//     contactPersonFullname: "Robert",
//     contactPersonOccupation: "Product Designer",
//     contactPersonCompany: "Design Co.",
//     contactPersonImage: "",
//     created_at: new Date("2023-01-17T16:30:00"),
//     updated_at: new Date("2023-01-17T16:30:00"),
//     tag: CONTACT_TAG_TYPE.COLLEAGUE,
//     note: "SIM student",
//   },
//   {
//     contactID: "4",
//     userCardID: "1",
//     contactPersonCardID: "3",
//     contactPersonID: "3",
//     contactPersonFullname: "Emily",
//     contactPersonOccupation: "Software Architect",
//     contactPersonCompany: "Tech Pioneers",
//     contactPersonImage: "",
//     created_at: new Date("2023-01-18T09:00:00"),
//     updated_at: new Date("2023-01-18T09:00:00"),
//     tag: CONTACT_TAG_TYPE.CLIENT,
//     note: "SIM student",
//   },
//   {
//     contactID: "5",
//     userCardID: "1",
//     contactPersonCardID: "4",
//     contactPersonID: "4",
//     contactPersonFullname: "David",
//     contactPersonOccupation: "Operations Manager",
//     contactPersonCompany: "SupplyChain Solutions",
//     contactPersonImage: "",
//     created_at: new Date("2023-02-01T11:30:00"),
//     updated_at: new Date("2023-02-01T11:30:00"),
//     tag: CONTACT_TAG_TYPE.SUPPLIER,
//     note: "SIM student",
//   },
//   {
//     contactID: "6",
//     userCardID: "1",
//     contactPersonCardID: "5",
//     contactPersonID: "5",
//     contactPersonFullname: "Sarah",
//     contactPersonOccupation: "Business Analyst",
//     contactPersonCompany: "Enterprise Consulting",
//     contactPersonImage: "",
//     created_at: new Date("2023-02-05T10:45:00"),
//     updated_at: new Date("2023-02-05T10:45:00"),
//     tag: CONTACT_TAG_TYPE.INVESTOR,
//     note: "SIM student",
//   },
//   {
//     contactID: "7",
//     userCardID: "1",
//     contactPersonCardID: "6",
//     contactPersonID: "6",
//     contactPersonFullname: "Michael",
//     contactPersonOccupation: "Legal Counsel",
//     contactPersonCompany: "Lawyers United",
//     contactPersonImage: "",
//     created_at: new Date("2023-02-10T12:30:00"),
//     updated_at: new Date("2023-02-10T12:30:00"),
//     tag: CONTACT_TAG_TYPE.EMPLOYEE,
//     note: "SIM student",
//   },
//   {
//     contactID: "8",
//     userCardID: "1",
//     contactPersonCardID: "7",
//     contactPersonID: "7",
//     contactPersonFullname: "Olivia",
//     contactPersonOccupation: "Data Scientist",
//     contactPersonCompany: "Data Insights",
//     contactPersonImage: "",
//     created_at: new Date("2023-02-15T13:00:00"),
//     updated_at: new Date("2023-02-15T13:00:00"),
//     tag: CONTACT_TAG_TYPE.VENDOR,
//     note: "SIM student",
//   },
//   {
//     contactID: "9",
//     userCardID: "1",
//     contactPersonCardID: "8",
//     contactPersonID: "8",
//     contactPersonFullname: "Sophia",
//     contactPersonOccupation: "Chief Technology Officer",
//     contactPersonCompany: "Tech Enterprises",
//     contactPersonImage: "",
//     created_at: new Date("2023-03-01T09:30:00"),
//     updated_at: new Date("2023-03-01T09:30:00"),
//     tag: CONTACT_TAG_TYPE.FAMILY,
//     note: "SIM student",
//   },
//   {
//     contactID: "10",
//     userCardID: "1",
//     contactPersonCardID: "9",
//     contactPersonID: "9",
//     contactPersonFullname: "Lucas",
//     contactPersonOccupation: "Customer Support Lead",
//     contactPersonCompany: "SupportNow",
//     contactPersonImage: "",
//     created_at: new Date("2023-03-05T11:15:00"),
//     updated_at: new Date("2023-03-05T11:15:00"),
//     tag: CONTACT_TAG_TYPE.FRIEND,
//     note: "SIM student",
//   },
//   {
//     contactID: "11",
//     userCardID: "1",
//     contactPersonCardID: "10",
//     contactPersonID: "10",
//     contactPersonFullname: "Grace",
//     contactPersonOccupation: "HR Director",
//     contactPersonCompany: "Global Enterprises",
//     contactPersonImage: "",
//     created_at: new Date("2023-03-07T15:00:00"),
//     updated_at: new Date("2023-03-07T15:00:00"),
//     tag: CONTACT_TAG_TYPE.COLLEAGUE,
//     note: "SIM student",
//   },
//   {
//     contactID: "12",
//     userCardID: "1",
//     contactPersonCardID: "11",
//     contactPersonID: "11",
//     contactPersonFullname: "Daniel",
//     contactPersonOccupation: "UI/UX Designer",
//     contactPersonCompany: "Creative Vision",
//     contactPersonImage: "",
//     created_at: new Date("2023-03-10T17:45:00"),
//     updated_at: new Date("2023-03-10T17:45:00"),
//     tag: CONTACT_TAG_TYPE.CLIENT,
//     note: "SIM student",
//   },
//   {
//     contactID: "13",
//     userCardID: "1",
//     contactPersonCardID: "12",
//     contactPersonID: "12",
//     contactPersonFullname: "Ella",
//     contactPersonOccupation: "Financial Analyst",
//     contactPersonCompany: "FinCorp",
//     contactPersonImage: "",
//     created_at: new Date("2023-03-15T10:00:00"),
//     updated_at: new Date("2023-03-15T10:00:00"),
//     tag: CONTACT_TAG_TYPE.SUPPLIER,
//     note: "SIM student",
//   },
//   {
//     contactID: "14",
//     userCardID: "1",
//     contactPersonCardID: "13",
//     contactPersonID: "13",
//     contactPersonFullname: "James",
//     contactPersonOccupation: "Business Consultant",
//     contactPersonCompany: "ConsultPro",
//     contactPersonImage: "",
//     created_at: new Date("2023-03-20T12:30:00"),
//     updated_at: new Date("2023-03-20T12:30:00"),
//     tag: CONTACT_TAG_TYPE.INVESTOR,
//     note: "SIM student",
//   },
// ];
//.............................................................

//........................dummy chart data to return.......................
export const chartData = [
  { date: new Date("2024-04-01"), view: 222, connection: 150 },
  { date: new Date("2024-04-02"), view: 97, connection: 180 },
  { date: new Date("2024-04-03"), view: 167, connection: 167 },
  { date: new Date("2024-04-04"), view: 260, connection: 260 },
  { date: new Date("2024-04-05"), view: 373, connection: 290 },
  { date: new Date("2024-04-06"), view: 301, connection: 340 },
  { date: new Date("2024-04-07"), view: 245, connection: 180 },
  { date: new Date("2024-04-08"), view: 409, connection: 320 },
  { date: new Date("2024-04-09"), view: 59, connection: 110 },
  { date: new Date("2024-04-10"), view: 261, connection: 190 },
  { date: new Date("2024-04-11"), view: 327, connection: 350 },
  { date: new Date("2024-04-12"), view: 292, connection: 210 },
  { date: new Date("2024-04-13"), view: 342, connection: 380 },
  { date: new Date("2024-04-14"), view: 137, connection: 220 },
  { date: new Date("2024-04-15"), view: 120, connection: 170 },
  { date: new Date("2024-04-16"), view: 138, connection: 190 },
  { date: new Date("2024-04-17"), view: 446, connection: 360 },
  { date: new Date("2024-04-18"), view: 364, connection: 410 },
  { date: new Date("2024-04-19"), view: 243, connection: 180 },
  { date: new Date("2024-04-20"), view: 89, connection: 150 },
  { date: new Date("2024-04-21"), view: 137, connection: 200 },
  { date: new Date("2024-04-22"), view: 224, connection: 170 },
  { date: new Date("2024-04-23"), view: 138, connection: 230 },
  { date: new Date("2024-04-24"), view: 387, connection: 290 },
  { date: new Date("2024-04-25"), view: 215, connection: 250 },
  { date: new Date("2024-04-26"), view: 75, connection: 130 },
  { date: new Date("2024-04-27"), view: 383, connection: 420 },
  { date: new Date("2024-04-28"), view: 122, connection: 180 },
  { date: new Date("2024-04-29"), view: 315, connection: 240 },
  { date: new Date("2024-04-30"), view: 454, connection: 380 },
  { date: new Date("2024-05-01"), view: 165, connection: 220 },
  { date: new Date("2024-05-02"), view: 293, connection: 310 },
  { date: new Date("2024-05-03"), view: 247, connection: 190 },
  { date: new Date("2024-05-04"), view: 385, connection: 420 },
  { date: new Date("2024-05-05"), view: 481, connection: 390 },
  { date: new Date("2024-05-06"), view: 498, connection: 520 },
  { date: new Date("2024-05-07"), view: 388, connection: 300 },
  { date: new Date("2024-05-08"), view: 149, connection: 210 },
  { date: new Date("2024-05-09"), view: 227, connection: 180 },
  { date: new Date("2024-05-10"), view: 293, connection: 330 },
  { date: new Date("2024-05-11"), view: 335, connection: 270 },
  { date: new Date("2024-05-12"), view: 197, connection: 240 },
  { date: new Date("2024-05-13"), view: 197, connection: 160 },
  { date: new Date("2024-05-14"), view: 448, connection: 490 },
  { date: new Date("2024-05-15"), view: 473, connection: 380 },
  { date: new Date("2024-05-16"), view: 338, connection: 400 },
  { date: new Date("2024-05-17"), view: 499, connection: 420 },
  { date: new Date("2024-05-18"), view: 315, connection: 350 },
  { date: new Date("2024-05-19"), view: 235, connection: 180 },
  { date: new Date("2024-05-20"), view: 177, connection: 230 },
  { date: new Date("2024-05-21"), view: 82, connection: 140 },
  { date: new Date("2024-05-22"), view: 81, connection: 120 },
  { date: new Date("2024-05-23"), view: 252, connection: 290 },
  { date: new Date("2024-05-24"), view: 294, connection: 220 },
  { date: new Date("2024-05-25"), view: 201, connection: 250 },
  { date: new Date("2024-05-26"), view: 213, connection: 170 },
  { date: new Date("2024-05-27"), view: 420, connection: 460 },
  { date: new Date("2024-05-28"), view: 233, connection: 190 },
  { date: new Date("2024-05-29"), view: 78, connection: 130 },
  { date: new Date("2024-05-30"), view: 340, connection: 280 },
  { date: new Date("2024-05-31"), view: 178, connection: 230 },
  { date: new Date("2024-06-01"), view: 178, connection: 200 },
  { date: new Date("2024-06-02"), view: 470, connection: 410 },
  { date: new Date("2024-06-03"), view: 103, connection: 160 },
  { date: new Date("2024-06-04"), view: 439, connection: 380 },
  { date: new Date("2024-06-05"), view: 88, connection: 140 },
  { date: new Date("2024-06-06"), view: 294, connection: 250 },
  { date: new Date("2024-06-07"), view: 323, connection: 370 },
  { date: new Date("2024-06-08"), view: 385, connection: 320 },
  { date: new Date("2024-06-09"), view: 438, connection: 480 },
  { date: new Date("2024-06-10"), view: 155, connection: 200 },
  { date: new Date("2024-06-11"), view: 92, connection: 150 },
  { date: new Date("2024-06-12"), view: 492, connection: 420 },
  { date: new Date("2024-06-13"), view: 81, connection: 130 },
  { date: new Date("2024-06-14"), view: 426, connection: 380 },
  { date: new Date("2024-06-15"), view: 307, connection: 350 },
  { date: new Date("2024-06-16"), view: 371, connection: 310 },
  { date: new Date("2024-06-17"), view: 475, connection: 520 },
  { date: new Date("2024-06-18"), view: 107, connection: 170 },
  { date: new Date("2024-06-19"), view: 341, connection: 290 },
  { date: new Date("2024-06-20"), view: 408, connection: 450 },
  { date: new Date("2024-06-21"), view: 169, connection: 210 },
  { date: new Date("2024-06-22"), view: 317, connection: 270 },
  { date: new Date("2024-06-23"), view: 480, connection: 530 },
  { date: new Date("2024-06-24"), view: 132, connection: 180 },
  { date: new Date("2024-06-25"), view: 141, connection: 190 },
  { date: new Date("2024-06-26"), view: 434, connection: 380 },
  { date: new Date("2024-06-27"), view: 448, connection: 490 },
  { date: new Date("2024-06-28"), view: 144, connection: 149 },
  { date: new Date("2024-06-29"), view: 160, connection: 109 },
  { date: new Date("2024-06-30"), view: 442, connection: 446 },
];

//.............................................................
